config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  post 'sessions/create'

  get 'applicants/new'

  post 'applicants/create'

  resources :owners do
      collection do
        get 'list'
      end
  end

  resources :houses do

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :houses
  enum sex: [:女, :男]
  enum active: [:無効, :有効]
  scope :by_id, -> (id) {where('id = ?', id) unless id.blank?}
  scope :by_name, -> (name) {where('name = ?', name) unless name.blank?}
  scope :by_email, -> (email) {where('email = ?', email) unless email.blank?}
  scope :by_active, -> (active) {where('active = ?', active) unless active.blank?}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to sessions_new_path
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  PAGE_SIZE = 3.freeze
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :load_house, only: [:show]

  def new
    @house = House.new
  end

  def show
    @house
  end

  def create
    @house = House.new(house_params)
    if @house.save
      render @house
    else
      render json: {errors: @house.errors}
    end
  end

  private
  def house_params
    params.require(:house).permit("name,address,city,type,guest_count,bedroom_count,
                  bed_count,bathroom_count,introduce,map_url,checkin_from,checkout_to,active,owner_id")
  end

  def load_house
    @house = House.find(params[:id])
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :load_owner, only: [:show, :edit, :update, :destroy]

  def index
    page = params[:page]
    @owners = Owner.where(deleted_at: nil)
                  .select("id,name,email,active")
                  .paginate(page: page, per_page: ApplicationController::PAGE_SIZE)
                  .by_id(params[:owner][:id])
                  .by_name(params[:name])
                  .by_email(params[:email])
                  .by_active(params[:active])
    # 再写一个render的话，会报Template is missing错误
    # render @owners
  end

  # 返回json的用法，json型的数据不知道怎么取到select里
  # def list
  #   owners = Owner.where(deleted_at: nil)
  #   owner_list = []
  #   owners.each do |owner|
  #     owner_list << {:key => owner.id, :value => owner.name}
  #   end
  #   # 下面的两种方法都可以，发送json格式，第一种包了一层
  #   # render json: {owner_list: owner_list}
  #   render :json => owner_list.to_json
  # end

  def list
    # @owner_list = Owner.where(deleted_at: nil)
    #                    .select("id,name")
    def list
      owners = Owner.where(deleted_at: nil)
      @owner_list = []
      owners.each do |owner|
        owner_list << {:key => owner.id, :value => owner.name}
      end
      # 下面的两种方法都可以，发送json格式，第一种包了一层
      # render json: {owner_list: owner_list}
      render :json => @owner_list.to_json
    end
  end

  def show
    # @owner = Owner.find(params[:id])
    @owner
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to @owner
    else
      render 'new'
    end
  end

  def edit
    @owner
  end

  def update
    if @owner.update(owner_params)
      redirect_to @owner
    else
      render 'edit'
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.deleted_at = Time.now
    if @owner.save!
      redirect_to owners_path
    else
    end

  end

  private
  def owner_params
    params.require(:owner).permit(:name, :email, :sex, :address, :tel, :active)
  end

  def load_owner
    @owner = Owner.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: user_params[:name]).try(:authenticate, user_params[:password])
    if user
      render plain: sprintf("welcome, %s!", user.name)
    else
      flash.now[:login_error] = "invalid username or password"
      render "new"
    end
  end

  private
  def user_params
    params.require(:session).permit(:name, :password)
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/applicants/create.html.erb
<h1>Applicants#create</h1>
<p>Find me in app/views/applicants/create.html.erb</p>

app/views/applicants/new.html.erb
<!-- app/views/applicants/new.html.erb -->

<h1>注册</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, url: :applicants_create do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p><%= f.button "提交" %></p>
<% end %>

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>

  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@house.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :物件名 %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :オナー %><br>
    <%= f.text_field :owner_id %>
  </p>
  <p>
    <%= f.label :住所 %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :物件タイプ %><br>
    <%= f.text_field :type %>
  </p>
  <p>
    <%= f.label :ゲスト人数 %><br>
    <%= f.text_field :guest_count %>
  </p>
  <p>
    <%= f.label :寝室数 %><br>
    <%= f.text_field :bedroom_count %>
  </p>
  <p>
    <%= f.label :ベッド台数 %><br>
    <%= f.text_field :bed_count %>
  </p>
  <p>
    <%= f.label :バスルーム %><br>
    <%= f.text_field :bathroom_count %>
  </p>

  <p>
    <%= f.label :チェックイン時間 %><br>
    <%= f.text_field :checkin_from %>
  </p>
  <p>
    <%= f.label :チェックアウト時間 %><br>
    <%= f.text_field :checkout_to %>
  </p>
  <p>
    <%= f.label :地図URL %><br>
    <%= f.text_field :map_url %>
  </p>
  <p>
    <%= f.label :有効・無効 %><br>
    <%= f.text_field :active %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/houses/new.html.erb
<h1>New House!!!</h1>
<%= render 'form' %>
<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<h1> Details</h1>
<p>
  <strong>
    物件名
  </strong>
  <%= @house.name %>
</p>

<p>
  <strong>
    オナー
  </strong>
  <%= @house.owner_id %>
</p>
<p>
  <strong>
    住所
  </strong>
  <%= @house.address %>
</p>

<p>
  <strong>
    物件タイプ
  </strong>
  <%= @house.type %>
</p>
<p>
  <strong>
    ゲスト人数
  </strong>
  <%= @house.guest_count %>
</p>
<p>
  <strong>
    寝室数
  </strong>
  <%= @house.bedroom_count %>
</p>

<p>
  <strong>
    ベッド台数
  </strong>
  <%= @house.bed_count %>
</p>
<p>
  <strong>
    バスルーム
  </strong>
  <%= @house.bathroom_count %>
</p>

<p>
  <strong>
    チェックイン時間
  </strong>
  <%= @house.checkin_from %>
</p>
<p>
  <strong>
    チェックアウト時間
  </strong>
  <%= @house.checkout_to %>
</p>
<!--<p>-->
  <!--<strong>-->
    <!--基本料金（一泊）-->
  <!--</strong>-->
  <!--<%= @house.charge %>-->
<!--</p>-->
<!--<p>-->
  <strong>
    地図URL
  </strong>
  <%= @house.map_url %>
</p>
<p>
  <strong>
    有効・無効
  </strong>
  <%= @house.active %>
</p>
<%= link_to 'Back', owners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>

  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@owner.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @owner.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :氏名 %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :メールアドレス %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :性別 %><br>
    <%= f.radio_button  :sex, :"男" %>
    <%= f.label :男 %>
    <%= f.radio_button  :sex, :"女" %>
    <%= f.label :女 %><br>
  </p>

  <p>
    <%= f.label :住所 %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :電話番号 %><br>
    <%= f.text_field :tel %>
  </p>

  <p>
    <%= f.radio_button  :active, :"有効" %>
    <%= f.label :有効 %>
    <%= f.radio_button  :active, :"無効" %>
    <%= f.label :無効 %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/owners/_navbar.html.erb
<div class="nav navbar-nav navbar-left">
  <%= form_tag "#" , :method => :get do %>
    <div class="input-group" id="search-id" >
      <%= @owner_list = Owner.where(deleted_at: nil)
          collection_select(:owner, :id, @owner_list, :id, :name, options ={:prompt => "-Select a owner"}, :class =>"owner") %>
      <input type="text" class="form-control" name="name" value="<%= params[:name] %>" placeholder="name" width="400">
      <input type="text" class="form-control" name="email" value="<%= params[:email] %>" placeholder="email" width="400">
      <input type="text" class="form-control" name="active" value="<%= params[:active] %>" placeholder="active" width="400">
      <button class="btn btn-default" type="submit" h>
        <i class="glyphicon glyphicon-search"></i>
        检索
      </button>
      <div class="input-group-btn">

      </div>
    </div>
  <% end %>
</div>

app/views/owners/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>
<h1>Do not need restart</h1>
<%= link_to 'New owner', new_owner_path %>
<%= render 'navbar'%>
<table>
  <tr>
    <th>
      氏名
    </th>
    <th>
      メールアドレス
    </th>
    <th>
      有効・無効
    </th>
  </tr>
  <% @owners.each do |owner| %>
    <tr>
      <td><%= owner.name %>
      </td>
      <td><%= owner.email %>
      </td>
      <td><%= owner.active %>
      </td>
      <td><%= link_to 'Show', owner_path(owner) %>
      <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
      <td><%= link_to 'Destroy', owner_path(owner), method: :delete, data: {confirm: 'Are you sure?'} %>
      <td>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate @owners ,:previous_label => t(:前のページ), :next_label => t(:次のページ)%>

app/views/owners/new.html.erb
<h1>New Owner!!!</h1>
<%= render 'form' %>
<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<h1>Owner Details</h1>
<p>
  <strong>
    氏名
  </strong>
  <%= @owner.name %>
</p>

<p>
  <strong>
    メールアドレス
  </strong>
  <%= @owner.email %>
</p>
<p>
  <strong>
    性別
  </strong>
  <%= @owner.sex %>
</p>

<p>
  <strong>
    住所
  </strong>
  <%= @owner.address %>
</p>
<p>
  <strong>
    電話番号
  </strong>
  <%= @owner.tel %>
</p>

<p>
  <strong>
    有効・無効
  </strong>
  <%= @owner.active %>
</p>
<%= link_to 'Back', owners_path %>